"""CLI.
  python -m worker check                      # step 0: models, context, tok/s
  python -m worker enqueue owner/repo [ref]   # add a job
  python -m worker run-once                   # claim one job, process, exit
  python -m worker serve                      # poll loop
  python -m worker local <path> [out]         # generate docs for a local dir, no GitHub
  python -m worker jobs                       # dump queue
  python -m worker webhook                    # GitHub webhook receiver (install/push/marketplace)
  python -m worker accounts                   # dump account -> plan table
"""
import shutil
import sys
import time
from pathlib import Path

from . import github, webhook
from .accounts import Accounts
from .config import Config
from .generate import Generator
from .ingest import RepoTooLarge, scan
from .llm import LocalBackend, Router
from .log import JobLog, info
from .queue import SqliteQueue


def cmd_check(cfg):
    b = LocalBackend(cfg.local_base_url, cfg.local_api_key, cfg.local_model, cfg.local_enable_thinking)
    print("model:", b.model, " max_model_len:", b.max_model_len, " thinking:", b.enable_thinking)
    t0 = time.time()
    text, u = b.chat([{"role": "user", "content": "Explain git rebase in ~300 words."}], 400)
    dt = time.time() - t0
    print(f"in={u.prompt} out={u.completion} wall={dt:.1f}s  {u.completion / dt:.1f} tok/s")
    print("sample:", text[:120].replace("\n", " "))


def _rmtree(p: Path):
    if p.exists():
        shutil.rmtree(p, onexc=lambda f, x, e: (Path(x).chmod(0o700), f(x)))


def process(cfg, router, jlog, job, queue_depth, plan="free"):
    t0 = time.time()
    backend = router.pick(queue_depth, plan)
    dest = cfg.work_dir / job.repo.replace("/", "__")
    _rmtree(dest)
    rec = dict(job=job.id, repo=job.repo, model=backend.model, backend=backend.name, plan=plan)
    try:
        inst = job.installation_id or cfg.gh_installation_id
        token = github.installation_token(cfg.gh_app_id, cfg.gh_private_key_path, inst)
        meta = github.repo_info(token, job.repo)
        base = job.ref or meta["default_branch"]
        sha = github.clone(token, job.repo, base, dest)
        snap = scan(dest, cfg.max_repo_bytes, cfg.max_files, cfg.max_file_bytes)
        info("scanned", files=len(snap.files), bytes=snap.total_bytes, skipped_dirs=snap.skipped_dirs)
        ctx_budget = int(getattr(backend, "max_model_len", 32768) * 0.6)
        gen = Generator(backend, snap, job.repo, cfg.max_file_bytes, ctx_budget)
        res = gen.run()
        for rel, content in res.files.items():
            p = dest / rel
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(content, encoding="utf-8", newline="\n")
        # rerun = same branch, force-push
        msg = f"docs: regenerate (source {sha[:7]})"
        new_sha = github.commit_and_push(token, dest, cfg.docs_branch, msg, list(res.files))
        if new_sha is None:
            # generated docs identical to what's on `base` (e.g. the docs PR was just merged):
            # nothing to push and an empty PR would be rejected, so stop here
            rec.update(status="no_change", files_sent=res.files_sent, tokens_in=res.usage.prompt,
                       tokens_out=res.usage.completion, calls=res.calls, wall_s=round(time.time() - t0, 1))
            router.spend.add(backend.cost(res.usage))
            jlog.write(**rec)
            info("job done, no doc changes", repo=job.repo)
            return "no_change"
        body = (f"Auto-generated documentation from `{base}` @ `{sha[:7]}`.\n\n"
                f"Files: {', '.join(res.files)}\n\n"
                f"Model: `{backend.model}` · {res.calls} calls · "
                f"{res.usage.prompt} in / {res.usage.completion} out tokens.\n\n"
                "Re-running the worker force-pushes this branch; review then merge or close.\n\n"
                "🤖 Generated by docbot")
        url, created = github.ensure_pr(token, job.repo, cfg.docs_branch, base,
                                        "docs: auto-generated documentation", body)
        rec.update(status="done", pr=url, pr_created=created, pushed=bool(new_sha),
                   files_sent=res.files_sent, tokens_in=res.usage.prompt,
                   tokens_out=res.usage.completion, calls=res.calls, wall_s=round(time.time() - t0, 1))
        router.spend.add(backend.cost(res.usage))
        jlog.write(**rec)
        info("job done", repo=job.repo, pr=url, wall_s=rec["wall_s"])
        return url
    except RepoTooLarge as e:
        rec.update(status="too_large", error=str(e), wall_s=round(time.time() - t0, 1))
        jlog.write(**rec)
        raise
    except Exception as e:
        rec.update(status="error", error=repr(e), wall_s=round(time.time() - t0, 1))
        jlog.write(**rec)
        raise
    finally:
        _rmtree(dest)


def cmd_local(cfg, path, out="out"):
    """Dry run against a local checkout; writes docs to ./out. No GitHub."""
    b = LocalBackend(cfg.local_base_url, cfg.local_api_key, cfg.local_model, cfg.local_enable_thinking)
    t0 = time.time()
    snap = scan(Path(path), cfg.max_repo_bytes, cfg.max_files, cfg.max_file_bytes)
    info("scanned", files=len(snap.files), bytes=snap.total_bytes)
    gen = Generator(b, snap, Path(path).resolve().name, cfg.max_file_bytes, int(b.max_model_len * 0.6))
    res = gen.run()
    for rel, content in res.files.items():
        p = Path(out) / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(content, encoding="utf-8", newline="\n")
    JobLog(cfg.log_dir).write(job="local", repo=str(path), model=b.model, status="done",
                              files_sent=res.files_sent, tokens_in=res.usage.prompt,
                              tokens_out=res.usage.completion, calls=res.calls,
                              wall_s=round(time.time() - t0, 1))
    print(f"wrote {len(res.files)} files to {out}/ in {time.time() - t0:.0f}s; "
          f"{res.calls} calls, {res.usage.prompt} in / {res.usage.completion} out")


def main(argv):
    cfg = Config.from_env()
    cmd = argv[0] if argv else "help"
    if cmd == "check":
        return cmd_check(cfg)
    if cmd == "local":
        return cmd_local(cfg, *argv[1:3])
    q = SqliteQueue(cfg.queue_path)
    acct = Accounts(cfg.queue_path)
    if cmd == "webhook":
        q.close(); acct.close()
        return webhook.serve(cfg)
    if cmd == "accounts":
        for row in acct.all():
            print("\t".join(str(c or "") for c in row))
        return
    if cmd == "enqueue":
        j = q.enqueue(argv[1], cfg.gh_installation_id, argv[2] if len(argv) > 2 else "")
        print("queued", j.id, j.repo)
        return
    if cmd == "jobs":
        print(q.dump())
        return
    if cmd in ("run-once", "serve"):
        router, jlog = Router(cfg), JobLog(cfg.log_dir)
        while True:
            job = q.claim()
            if job:
                try:
                    plan = acct.plan(job.repo.split("/")[0])
                    url = process(cfg, router, jlog, job, q.depth(), plan)
                    q.complete(job.id, url)
                except Exception as e:
                    info("job failed", repo=job.repo, err=repr(e))
                    q.fail(job.id, repr(e), retry=job.attempts < 2 and not isinstance(e, RepoTooLarge))
            if cmd == "run-once":
                return
            if not job:
                time.sleep(cfg.poll_seconds)
    print(__doc__)


if __name__ == "__main__":
    main(sys.argv[1:])
